version: "3.3"

services:
  argus-front:
    image: ccr.ccs.tencentyun.com/zhangyancheng/argus-front:1.0
    container_name: argus_front
    restart: always
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
    networks:
      - argus_frontend
      - argus_shared

networks:
  argus_frontend:
  argus_shared:
    external: true
