version: "3.3"

services:
  argus-front:
    build:
      context: ..
      dockerfile: ops/frontend.Dockerfile
    container_name: argus_front
    restart: always
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
    networks:
      - argus_frontend
      - argus_shared

networks:
  argus_frontend:
  argus_shared:
    external: true
