version: "3.3"

services:
  argus-front:
    build:
      context: ..
      dockerfile: ops/frontend.Dockerfile
    container_name: argus_front
    restart: always
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - argus_frontend

networks:
  argus_frontend:
