version: "3.3"

services:
  argus-front:
    image: ${ARGUS_FRONT_IMAGE:-ccr.ccs.tencentyun.com/zhangyancheng/argus-front:1.0}
    build:
      context: ..
      dockerfile: ops/frontend.Dockerfile
    container_name: argus_front
    restart: always
    ports:
      - "${ARGUS_FRONT_PORT:-8000}:80"
    environment:
      TZ: Asia/Shanghai
    networks:
      - argus_frontend

networks:
  argus_frontend:
